name: HCL DevOps Test UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL DevOps Test UI
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/devops-test-ui-action@main
           with:
            projectDirectory: 
            scriptName: 
            iterationCount:           
            logFormat: 
            userArguments:
